sudo: required
services:
  - docker
before_script:
  - sudo service docker stop
  - mkdir /etc/docker/ -p
  - echo "{\"insecure-registries\":[\"${DOCKER_SERVER}\"]}" > daemon.json
  - sudo cp daemon.json /etc/docker/daemon.json
  - sudo service docker start
  - sudo apt-get install sshpass
script:
  - docker-compose build
  - echo "${DOCKER_PASSWORD}" | docker login ${DOCKER_SERVER} --username "${DOCKER_USERNAME}" --password-stdin  
  - docker tag dockerdeploymentdemo/static_website ${DOCKER_SERVER}/dockerdeploymentdemo/static_website
  - docker push ${DOCKER_SERVER}/dockerdeploymentdemo/static_website
after_script:
  - sed -i "s/\${DOCKER_PASSWORD}/${DOCKER_PASSWORD}/g" deploy_script.sh
  - sed -i "s/\${DOCKER_USERNAME}/${DOCKER_USERNAME}/g" deploy_script.sh
  - sed -i "s/\${DOCKER_SERVER}/${DOCKER_SERVER}/g" deploy_script.sh
  - sed -i "s/\${DOCKER_SERVER}/${DOCKER_SERVER}/g" docker-compose.production.yml
  - sshpass -p ${DEPLOY_PASSWORD} ssh ${DEPLOY_USERNAME}@${DEPLOY_SERVER} 'mkdir ~/docker_deployment_demo/'
  - sshpass -p ${DEPLOY_PASSWORD} scp -o stricthostkeychecking=no ./deploy_script.sh ${DEPLOY_USERNAME}@${DEPLOY_SERVER}:~/docker_deployment_demo/deploy_script.sh
  - sshpass -p ${DEPLOY_PASSWORD} scp -o stricthostkeychecking=no ./docker-compose.production.yml ${DEPLOY_USERNAME}@${DEPLOY_SERVER}:~/docker_deployment_demo/docker-compose.production.yml
  